# DNS Settings
port=0

# DHCP Settings
dhcp-range=192.168.1.0,proxy
dhcp-option=option:router,192.168.1.254
dhcp-boot=pxelinux.0,pxeserver,192.168.1.24

# TFTP Settings
enable-tftp
tftp-root=/var/tftpboot
tftp-single-port

pxe-service=net:#ipxe,x86PC,"test",pxelinux.0
